context:
  name: ccflow-email
  version: "0.2.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/ccflow_email/ccflow_email-${{ version }}.tar.gz
  sha256: 21e4c19186c55932253a171f2c15f90454a89ed7caa3dd452f67bc1c6079e818

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - ccflow
    - emails

tests:
  - python:
      imports:
        - ccflow_email
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: ccflow models for email
  homepage: https://github.com/1kbgz/ccflow-email
  repository: https://github.com/1kbgz/ccflow-email

extra:
  recipe-maintainers:
    - timkpaine
